I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    image hiyori = Live2D("Resources/hiyori", base=.6, loop = True, fade=True)
  File "game/script.rpy", line 9, in <module>
    image hiyori = Live2D("Resources/hiyori", base=.6, loop = True, fade=True)
Exception: Could not load Live2D. b'Live2DCubismCore.dll' was not found.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    image hiyori = Live2D("Resources/hiyori", base=.6, loop = True, fade=True)
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 922, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 9, in <module>
    image hiyori = Live2D("Resources/hiyori", base=.6, loop = True, fade=True)
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 587, in __init__
    common = self.common
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 538, in common
    return self.create_common()
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 526, in create_common
    rv = Live2DCommon(self.filename, self.default_fade)
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 188, in __init__
    init()
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 95, in init
    onetime_init()
  File "C:\Users\24510\Downloads\renpy-8.2.1-sdk\renpy\gl2\live2d.py", line 68, in onetime_init
    raise Exception("Could not load Live2D. {} was not found.".format(dll))
Exception: Could not load Live2D. b'Live2DCubismCore.dll' was not found.

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.1.24030407
ChatWaifuL2D 2.0
Sun Apr  7 23:02:41 2024
